
object cons {

    def main(args : Array[String]) {

        val s =
            """
              |>Rosalind_2517
              |TATAGCTTTTAGGTAGATCAAAGAAAACACTCATATGGCGCTAGGATAGACAGGTGTAGT
              |AGGTTTCTCTCCGTCGCCTCTGAAATGTGTAAAGGTCCATCGCTCTGAGCGAAGGAGCAC
              |GATTTCCAAAGGTATATTCGTAATAGCTCCTGAACAGTCGAGAATATATGCACCTCGTGA
              |CGCTACAAGCTTGTACCGAGAATTGACGGTATACTGGGGAAAACACTCTAGTTAGACATA
              |TATCATCTTGACATCTCGCCTAATACCTTGACACGGAGCGCATGGTTAACGGCCATTTAC
              |GGTGTTGTGAAACCCATCTAGTGCTCCGCACGGTCGTTGGCGTTAGCTATGCTCTATCGA
              |TATGACTTCGGGACGTTATATATGTTAATAGTAGTAAATTGAGCGTCAGGGACCGGGGGT
              |CTTGCAAGTCCATAGCTACTGTGTAAGCTGTGGATGTTGATAAGTACAGGGGAAGGGTTT
              |GTTCGGCTTGGTATTTGCGTATCAGAGAAAGGAGCGTTCTTATCGGTCGTCACGTCTCCA
              |ACAACCGCTGGAGTACACATTTGCCCTGAGACCGTTCTCGCTTTTGATATAGTTCTTTAG
              |CATCATCGAGAAGTGCCGAGATACCGATAAACCGCCACAGAGTAGTCTCTGAGGCTCGCA
              |GTCGCGCCATCGCAGCATTCGGTAGAGCCTTGAAATTACCGAATCAAAGGACAAACACCC
              |GGCACCACTCGCGGAAATCTGGCGTTTAGCCTCCGGTGCATCGCATTGAAGCTCCTCGTC
              |CTAATCCCGGCATTATATACCGCGTCTTCAAACATGGGACCTCAGCCAACTAACCATAGT
              |AGTAGTGACGCGCTGGGGTCGGCCAATTGTCGCCGCAATTGGCGCCTCTGAATCCCCAGG
              |TAGACCTGGGTCGTCGTTATCAGTGATTATTCATCTCACGCTCCGTGTCCCCGAACGCAT
              |GCG
              |>Rosalind_7032
              |ACTGAAATCAACGTCACCGGACCTCCCCCAGATGCCTCTCTTTTGAACAATGCCACTGTT
              |CAAACACTATGGGTCAAGAAGTGAGGGAGAGAAATGGCTGCACACGACATTCTCAAACTG
              |CTGGTAGATTAGCATAGACTCGTGCTGATCTCTGCGCGTACGTGACAGGGGTGGAAAAGC
              |CATGAGGGCTGCACGTCACTTAATACCGTGATCAGCGTCCTTCTCGCAGATGAAAGGCAT
              |CAGACTAACTTTTAGCCAAACACTGAAAACTGTTGGGCGGGAGTACCTCGAGTCCGCCTC
              |CAAGGGGGTAGTTGGGGTTCAGTAGCTGGCTACAGGTGTAGTTGGCTAACTTGTTAGCTC
              |AGCTGGGTCGGACCCTCGTCAAGGTGAGCCTGTTCCTTATGTGCTTCAAATAAACGTGTG
              |CGAACAGGCTATAAACAGATAGGAATGATATAATCGTACTTTGCCGGCGGCAGATGGCAC
              |CATGAATTTTCAGCTAATTGTTAAAAACGGCCCCTGTGCCTTGTAAGTCAAAAGATCGCG
              |CGGAGTGAGAGTACAGAACCCCTGGGCACGATGTCACTGAAGCCGACGACGCTCCAATTG
              |CCCTGTTCCGTCCGGCTCTTAGTTTAAGGAATTCCTAATGAAAGGATATGATTACTATCT
              |GAGTGACAATGGTATAAAACATATAAGATGACCCTTTATCAAAGTTAGTAGCCCTCGTAA
              |ACCAGAGCGGTGCACAAGTATAGCAGAGGGGACGAATAGACTTTCTCCTAAGGTACTAGC
              |CAGCATCCTGAGGAATTCCACTGTTAGCAGGGACGTGAATGACTGCGGAGACCGTATTCA
              |TTGGAGCGTCGGGTAAGGAGTACTGTTTGCCTTCTCACTTTCTTTCCACATCTGGGAAGG
              |CCGAGAGGTACATAATCGATATTTAACTCGGGAGCGATTGATAGCCGGTTTATGGCGCGA
              |ATC
              |>Rosalind_1852
              |TCTCGCCAACCATTTGAAAATCTCTAACCAGTTAGTGGTTTGGGGTAACAGACCAGGCCC
              |GCACGGATTCTCGCCGCATGTGCAGGACGTATGGGGCGTCGATTAGGAAGTTGAGCTGCC
              |TAATGCGCACTAACCTATACAACGCTCTCAGGACGTATCGATCAAGTGGGTTCGCTACAA
              |TGTTCTTCTAGAAGTGCCGAAGTTGGAGCACGTATGTGCTTATCCGTAGGAGACTTGCGC
              |AGGCTGTAGTCGTACACCAGCGGTCGCGAGCCGCTGCAATGGTCCTGCTGGGCCGAGCAG
              |CTCAGATGGAACCTCTGCTTGCAGACTCTAACAACCCGAGAGTAGAACGGGGAGCGTTTT
              |AGGTTTCCTCCATTTTAGCGGCCGTATCTATACCTCTCACCCTAGTTGCAGACCACACAT
              |AAGGCGCCGGTCGGAGCTGCGCAACACGAGGCTAACCACCAGCCCGTGTGGCCTATTGCA
              |GATACAATTCCTCAAGCCTCAATCCTGCGAAAAGGGGAAGCCAGACTCCGATGCCGAAGC
              |CTCCAGAACGTATAACGATGCCTGGGAGGCGACAAGAAAATCATCCGATATCTATTAATA
              |CTAAATGGGGTAGTTCCTCCCTACCGAAGCCGCTCGCGCGGCTCTGATAAAATCCGACTC
              |TGAATCGACCAATGAGCTGCAGACTAGGATCCTACAGGACAGGTCAGAGGCCGTGGGATA
              |TATTCGAAGTACGCCGGCACAGCATATTTAGCGACGACCCCGCTGACCTGTACAAGTTGG
              |GCTTTACCACTCACCCGTTAGGGCAAATACCTCAGTATTCCTCCAAGAATCGTTCCACCC
              |ATAGATGGCAGTTAGATCCGAGACATGAAATTTGGTCCCATTGACTTGCCCGTTATGTGT
              |CTGAGGCTGAGCGTTGAGCTCCCAGTTCACCCTACCCCGTTTATAGCTGATGTTACATAC
              |AGA
              |>Rosalind_4010
              |TGCGCCAGCAGGTCGCGCAGCCTTAGACTCCGGTATTGGTCGGGTGACAATGCCGAAGAA
              |TTTGATATAGCATGCCACCGCCAAAATGCCCCGTATATGTAGTGTCTTCACTCGTGCGCG
              |ACGCTGACCCCGATCTCGTTTAATAAAATCGGAGCCAGCTGTTTGAACTTAAAACTACCA
              |GCGGCGGGTTATTCCTGGCGTCAACTCACCCGCGACACAGGCATGCGTTATGTATCCTAC
              |TTATAAAAGGGAAGCGGCCTTACATTCAACAAGTATGACTAGCCCATATTAAGTTAGGAA
              |TGGGGGGCAGTCAATATTATCCTCTGTAATGAGGGCGGCTAGATCACAGGTATTTGCGAA
              |CAGCGGGATGTCACACTACCTAGCCAAGCGATGCCAGGCGTTCATCCGCCCTATTGAGAC
              |CATCGTTCAGCGATCGTGGATACTGCGATTGCCAGAGCCTACATGTCCAGTTTTCTTCGT
              |GAATGCGGTGAGGCGAACTTGGTTTGCGACAAAATGTCTAGTGTTGTCTATTTTGGGCTG
              |CTCAAATTCTAGAAGAAGGCTTACATGCCTCGTTCACGCCGATACATCGTGGACATACTG
              |CGCATATAGATTGTCTGTACTTCCCGCTAGAATAGCAGCCGTTGCCAATTGGCAGGTGCG
              |ATCTACATAGACAACGATGGATGTAACCAAGGTGCACGGGCGGTCTCAAGCCAGCGCTTG
              |CGAAGCTATCGAGCTGAGATGCAGCCAGGGATCCGGAATGTCCCTCCGTGATTCTCGGTG
              |ACTCCCGAGTCTTCAAAATTACGAGGATAGGGCTCGGATTAACAGATTGGGGTACACGCT
              |CACGGTGCCGCAGTGTAGGTCTTCGGTGAAATATGGCGTTCGGTCTAGCGGAATCGAAAA
              |AGCTGGCCGTTGCTCTCCGTTTCGACAGGTATCACCATAGTCGATACCTTCCGTTTTGGT
              |AAG
              |>Rosalind_7483
              |TGTTGGTACGAATTCTAACCTGGCGTCCCTCCCTAATTTTTTGCAAAACCCGTGGCTGCT
              |ATGTCGTACACCATAAGTCGATGGTGAAAGGCTGCCAGTCACAGATTTCGTGAATCACCG
              |TCGACTTAGATAGAAAATACCGACCCAATAAGCCGCGAAAGTTTATAAGGTACCGAAAGT
              |TAAGGCGTGATGCACCGTTATGTATGGCCCATCTGCACGGTCCTGCGCGGTGCTCCGTAC
              |AGTATGATCTTTTTTTAGGATGCCAGTGCAAACTCCATGGTGGGGAGCATTAAGGCTCGT
              |AGGTCTTTGCTAAAATAAACGAATTCTTGTTAAAGTGTTCTTAAGACGCGTATCCCGGCC
              |TGCGCGCGCGATGTCGCGGGTCCGATCTCGGACGCCGCTCAATCGGACGGTCCCCCGATG
              |ACTCTATTGGCTAGGCAACCACCGACATAGGACGAAATTCCTGGCGCTCGTGCTTCGAAG
              |TATTTCTTTAATCTCAAGTCGGGCGGTCCAGTGTCCAGATCGTTTGACGGCGTGACAGTA
              |ATAAACCGGAAAAACCGCACGGATCTATTCATAAGCCCAACCTACACTCCGAGGGGACGA
              |TTGGCGCTCTGGCCGACCTTGTCATCTAATTCCAATCGGCTGCCCCCTGGGTGTTAACGC
              |CACCGAGTGACTAGACTATCCGGCAAGCTTATCTAACCGGCCGGCTCCTCCCTACAACCC
              |CGGACCAGGATCGAATTCAGGCGCCCAACGGTTCTAGTTTCTCGAATAAGGAAACAATGC
              |CCCCCAAATGATCTGGGACAGTCCAATCTAAGTCCTCGCCGAATTCGCTAAGAACTGCTA
              |GTGACACGTATGTATCACAACGTAGTAGTGCGCCCAGCAACGAGACATATGGCTCGGACC
              |ACCTAAGTGAAACCACACGCGTAGAGCGTATATGCCGGGGGCAGTTGCTATAGTGGGGTC
              |TGT
              |>Rosalind_0639
              |ACCCCGGCGCAACATCTATGTATCACAGAAGCTTGGTACGGCTATTTAACCCCGGACATT
              |GACTTCCAGAGGGAGTACAGCAACTCTCTCCTCCCTAAGCAGACCCGGCGTATATCCAGT
              |CCTACGGAAGCTTGTTAAGAATCGACCACAAACCAGGCGTTCCGCTCCACTACATACTTA
              |GGGACCTACCCTTTGATATACATTGCCAGCGGATGGGCTGACATTCTCTGGCCGAGGTAG
              |GGCAGCTCATCCCACGATACTTATGTGACTTGGGAGGGGGGTGGCGGTCTCCCCGGCGTC
              |TTATACCGATACCTGTTGGGCAGGGCAGAAGTCCTGGCGACATGGAAAACCCATCTTGAG
              |CTTACCTAATCAATCTTAGAGCGCGGGTAATAGCTGAGAAGAGGTACGTATTGAGGCAGG
              |CCCACCAGCGCAATTGTTACGCCAACCCTAATTGGGGCGAGATCGCCGACGGTTTGCAAC
              |TATCATATAGTGGAAACCCAGCTGCGGGCTGCACGGTAGGCCACCCGAGTATTACTCTTA
              |AAACTAGACTAGCAATCGCTGTAAACGGATAAGAAGAACTTAATATCTTTCCGTAATTGC
              |GTTAAGATCGACCACGGTCTCTCGGGATTACAGGGGGGAGCGCAGTGGACCCGCGCGGTA
              |CGTGTCCCAGATATACACGGTTTGTAACCAAGACTCGTCTAAAAGATTGTCTGGGCCTCG
              |GTTTTGTCACCTTTAGCTCTCAGATAGAGCCGTCGTGCGCGAGCAAAATTACTATTAGGG
              |GTAATCTAACACACAACTGGAATAGTTTTAAATGAACAATATGTGACTTCAGAAATATAC
              |CGTTCACAGAAAAGAGCTATGTTGCTGGTGGGTGCGACGGGGTTCCTGCAATCTTTTGAA
              |TTTTTCGGCTCTGCAAAGTGTGAAGCGGGCTTGGACACTATCCAAAGGGAGGTATACCAC
              |CAT
              |>Rosalind_7244
              |GCCGTGCCATGCGCGGAGGCAACTGGAGTCTCCCCTCCCGGATTCCTGACAGGACGCAGC
              |GTACAGACTTGATTCTAGTGGGAGGAGACTCAACTAGAAATCGAGAATCGTTGGTTGATC
              |TTAGAGCTCAAGTCGTGGCTGACCGATTCAGGTTACTACAGATCAAACAGGGCCGCCGGC
              |GTTAACTACCGATTGAGCTTCATCAGGAGTCAGGAGGAACACGGACTGCTCGCGAGAATT
              |AATTAGCGGATCTCACCTGCCTTGGTGATGACTACCAGTCAGCCGTCCACCTATCCCCAC
              |GGGGGGTACGCATTTGCATACTCTAGGCCTTGTAAGATATGAGGCTTGTTCTTCTTTTCG
              |CAGATGTGGTACATTTGACCCGCCTCGCCACAAGTCGGCCCATGTGCGACAAAAGATATC
              |CCCCTGGCTGTCAATACTCCATAAGTCACTATCGGTTAGTGGAGAAAGACTCTATCCCCT
              |TCTGGATGGTGGTATTAGCCCGGACAAGATTGACCTGAGTAGACCTTCAACCGGAGAGGA
              |AGGCCCTGGGCTTCTAGTTCGCGGCCTAGCGTGTTTGATGAGGTTCGACCTTGCATGGGC
              |GCGTGTAATTTACGCAGCGAAGTCGTCACCCTCCATGAACATGTATAGAGCTCTCATGAC
              |AAGTACCGGTCGATACCTTAACTCCGCCGTCAGTCGCCCGACAGGAGTATGGACACACAA
              |CCCGCGCTGTCCATAAGGGAAATTAATCGTAGATCACGCTTGGCGGTGCGCGCACTGCAA
              |AAGCGTCGTTTCACTCGACTCCTAAGCATGTAGCACGTTGACGGCTGAGTTACTATGATT
              |ATCGCTACCTGGATGGATGAAGCGGACGGAAGGATTTCTGTCAGCGTGAACGGCATCTGT
              |TGAACGCACTGCTGCGGTTATAATTGTAAAGCACTTCTGACATCACCGTGGCTACTGCGA
              |GGC
              |>Rosalind_8764
              |CTAGTGGAGAACCTGCGGCGGTTGACCCTGTCGCAGTCCTCGCCGCATTAAGACGGGGAC
              |TTCACGGGCGTGGCCTGACAAGTGATCGCTAGACGTCAAGTCCGCCGCCACAAAGGGAAA
              |TGGGCCTCTGGTAGCGTGAGAGAGTCTAGTGAGCGAACTGATCTGGATGAAATAAGAGAG
              |CTGTAGAAGACAATGCATCGGAATAATTTAGGGGCGGAGCGATCTAACGACGTGCCCATT
              |CCTAGCCTCCGCAAAACGGAAGGCACCGGCCTTCCGCGCCCGGTGATCGAAGCTGGCTTA
              |TTAGTTTGTTTCGTCGGAGCACTCACCCGTCGCTGGAACTGGTTTGTCCGAATTAGTAGG
              |AATAAACTACTCTGTGTTCCGTTGCCACGAATTGCGCGTGAGCGATTGTTCTGCGCAGAC
              |ATTGCCTGATTTTCGTCGCCTTAATAGGCACTGTTCACTAGCCACTGTAAAGATTGAGAG
              |CCTCCGGGTATTGGGCCATGTGACCGTTATCAGTAGTTTGTGCAGTTAATAGAGGATTGC
              |CTCGTTCCATGGCATTGCTCCTGAATTCCTACCGAGAACTCGAAACAGGATCTTTAATTA
              |ACTAGTGCACTTCCGCTAAGTTGAAGCCACGTGCTCTCAATCAAGCCCCAATCCTTAACA
              |GGCAGCGCGGTTCCACTGCCAGTCGCACTCAGAGGGCGACCGTCAGTGTACTCTTCCCCC
              |GCGAACTTGCCAATACATGATTGGGAATGTGATTAAGATGTGTCTCTCCTTACATAACCG
              |CCAGATGCATTGGAATGAGAACTGCCAATCTTGACACTAATCAGTTACCTCTGTGCCTGA
              |ATCCCACGCACGTTAACGGCGTACGCGCCAGTTAACTAGGTACATTGAGTCATGACGAAA
              |AATTAACGAAGTCAGTTTCATTAACGTTATGGTGAACTCTGGTATTCCAGCACCGAGGCT
              |TAC
              |>Rosalind_4925
              |TGAGGCCCCAGTACCGCAGCGTAAGCATGCACAAACATTTCATGCAGGTCACGGTTAGTA
              |CATGACAATCGGCCGAACAACTCTAAATGCAGCCACACACTCCGAGGACCTGGGGACGAT
              |GGTTTATCCTATACACAAAGGGTTCCAATGACCCAGGGGAGCGTACGGTTGCTACGGGAT
              |TCCGAGCCGCCGAAGATTTTACGGTGAAATGTTGGACGAGATGGGACCATTATAAATACT
              |ACCTCTTCGAGCGTGTGATCTATAAGTTTGTACACCGCCCTCCTTCAGGCGGGTAGTCAG
              |TTAGTTCCGGATCTGGGCCGGACTTGAAACCACATTAAGGAGCTCCATACCCTGGATGTG
              |AATAAGCGCATTTCTAATCAAGCTATGTTGCTATTTGAAGGACGATCGACGCATGGGACA
              |TTCTGATGTACCAGATAGGAATTTCCATCTTTTGTGCGGACTGTATGTTTTCCCACGTGG
              |TTATAGAAGGTGTTGGTTGCTGTAGGCGTTGAGCTTTCCGGAATAGGTGCCATGAACGCT
              |GAATCATCGGGCTTATTTAAACCAGCCAAATTTGAAGGGGTAGTACTGTTCGTCCCGTTA
              |CACGATGGTCCCGATAGATAAGGCTCCGCTAATAAGAATCAGTTTGCAGGGACGACGGGG
              |CGTCAGACTCTCACGAGGACAGAAGGGAGCAAGCAATATTACCGTAGAAATACGAAGTGC
              |ACCGAAGCCCGTTACTCTACTAAGGGATTTAAGCATGTTGTATGGAAGATTGTGACATAT
              |CATCCATTATCGAATTCAACTATATTCCTCTTCAGCCACTCAACCCCGGTCCGCCCGTTC
              |TATTACCTCATTGGCTGGTGGACCGTGCCTGGCCAGCCGGCTCATGCGGCACAGCAATGT
              |GATTTAAAGATTATCCGGGCCCGGACTACCTCAATTCGGCCGGGATATACCTGTGGGGTT
              |TAC
              |>Rosalind_9188
              |CCTATCTGGGGGAAACTGTGTCGATGCACACTGTAGTTCGCATATTAACTATCGATCATT
              |TGTTAGGCCGAAAGGATGGACCTGCGGGGTTATTTATACCTACCATTTCTGCTGTGAAAC
              |CTCAAGGCCCGCACACGCTGCTACTAAGGGTAGCCGATGAGGGCAACCCGCATTAAAGTG
              |GCAGTTCATTAAAACCTCTGAATCGTCGGAGCACGCACCAAAGACAAGGCGTCGGAATCC
              |AACTGTTTCTTGCCCCGGGTTTCGTAATTACCATAGTCGGCGACCAATGTACTGCGACCG
              |CGGACCTACATCAGCATAAGTTTACGGAACGAATGTTCTCCAAAGAGTCACGCCTCAATT
              |ACTTTTAAGGGTGTTTGTGAATACCATTTCCCGCATCCCGTATGAAGCTATCTGCGGTAT
              |TCCGTCCCCAGAGGTACGCCGTGTCTGCTCAAGGGGAATATTCGGCTAATTTTAGGTCTG
              |TCCGCCCAAAGACTGCTGCCACTGTGGACCTGTCATGCTGCGGCGGCAGGTTGTAGCCAG
              |CGGTTACCCCCGGGTCCGGTAACCTGCTCCCGGCCCTCTATTATAACACCTCCTGATGCC
              |TGACCTGCAGACACGTAGGGCCCCATGAGTCAGGCCGATTAAGGGCGGAGCCGGCAGGAG
              |GGAGGAAGGCTGGATACGCCGGTTAGAATATCGTTCTACGGGAGGATTGCTACGTAAGTC
              |CCGTCCTCGACAGTTTATGCGTGCTGTTGTTAAGCAGATGAAACGCAGCAAGCCCCGATG
              |CCATCGGTCAAAACTAAACCGTCATTCTCGCTCACCTCCGTACCTGCTGAGACACTTACG
              |AGGCACGTCTCCAGTCCTTGATTAAATATAGTATGCTCTTTTATGCTGCAGAACCGCTTG
              |GCTAATAGCTAGTTGCCAACGATCTACTTGATTGTACCGGTTTGGGTTGCAGGGTAGGAA
              |GCT
              |""".stripMargin

        case class ACGT(A : Int = 0, C : Int = 0, G : Int = 0, T : Int = 0)
        {
            def symbol = {
                val m = Array(A,C,G,T).max
                if (A == m) 'A' else
                if (C == m) 'C' else
                if (G == m) 'G' else
                            'T'
            }
        }

        val counters = (s split ">").tail.foldLeft(List.empty[ACGT]) { case (arr, x) =>
            val e = x split "\r\n"
            val seq = e.tail mkString ""

            val A = if (arr.isEmpty) List.fill(seq.length)(ACGT()) else arr

            A zip seq map { case (a, x) => x match {
                case 'A' => a.copy(A = a.A + 1)
                case 'C' => a.copy(C = a.C + 1)
                case 'G' => a.copy(G = a.G + 1)
                case 'T' => a.copy(T = a.T + 1)
            }}
        }

        println(counters map { _.symbol } mkString "")

        println("A: " + (counters map { _.A } mkString " "))
        println("C: " + (counters map { _.C } mkString " "))
        println("G: " + (counters map { _.G } mkString " "))
        println("T: " + (counters map { _.T } mkString " "))

    }

}
