
object gc {

    def main(args : Array[String]) {

        val s =
            """
              |>Rosalind_4040
              |TTGAGCGGCCTATTGCAGCATGGTACTGCCGCTAGAAGTAGATTCATCTGCGTTCCAAGA
              |GTATGTCAGCGCGGCTGTCGGTGGAGCTACCCTTCACTGTTTACCGGCCGTGACTGAATA
              |GGGCATGCACGTAATTTGCTAGTTAGGATATAAATTAGCAGTTATATCATCCTGCTGCAG
              |GGATCCACGCGTAGGCAAGAGTTTAATCCTTTACTTCAACCTTTTCAGCGTTGGAGTTAT
              |GATTCGTCTGGCCTATGTCAGATTGGTGTAGGACGTACACTTCTCATTACCACTGGTCTC
              |AGAGCACCATTAAGAGGTTGCGGAAGCGGGATTTTGTACTCCGAACGCCACAAGACCGTG
              |GTGGTTCACCCCTTGTACAGTAACGCAGTATCAGTCAATCGTCGAAGGGCTATCACCTGT
              |AACTGGGAACTTAAACTAATGCCTTCATAATTAAAACACGCCGTTGTGCCAGTCCTTCTT
              |GATAAAGCCCCACGGTACCAAGCCAACGTGTACCGCAGTCCGCTTCGGCATATGTTGACA
              |TTCGTACGTGTGCCTCTGCCCCAACAAATTTAACGCTTAGTCAAGTAATAAGATAACTAC
              |ATACCCCTCTCAGCGTAGCATGCCTTGGTCGTCCGATTCTATCCGGACTAGACTCGACAG
              |GTGTTTTGTCTAGGTGGCGCACCATCCATATAGTGCCGACAGTCCGATAAATTAGCTAAG
              |GGGTCAACTTTACACCAGGTTTGAATCGGTTCTACCCAGGAACAGTGCTCCCTCTCATAG
              |CAGCAACTGAAATTACCTTGATTACC
              |>Rosalind_8210
              |CAATGCGTCCTGGTACTCGACAAAGTCATTTTCACCCCACCTATCCTAAGCGTCGGATCA
              |TAGGTTGAAGGCAGAGATAACAGTCATTTATCCACAAAAGTCCGAACTAAAAGCGCTATA
              |CGGGTTCACTAATACACGAGATTATTAGCGCAGTAAGTCTCTCTTATAATTATTTGATAT
              |AGCATTGGGTTGACACTTAGGATGTACAACGAGTTGCTGGTGAGTCGAGTGAGAGCGGTG
              |GAGCTGTGTCTAGCTAACGTTGCGCAGCAGGTCCAACATCACTTTGTGTTCTAGCGGAGG
              |ACCTCCTAGCCTTCAAGATTTTTCTCACCTGTTATGGCTTCATTATCTGTGTAAGGGGAA
              |ATATACGACCCTCGCCCTAGGTGAAGAATCACCTATCAACCTAGATTCCTCGCGCACTGC
              |ACCAGTGCAGCCCTAGTTAGTGTACTGTGTAAGAAACCCATTTCTCTAATTGGTTAGCGA
              |TCACCGTTGAGGCTACTAATGCTCAATCGCAACACCATGCGATATAAGGTACTTTCGACA
              |GAATGTCGTGATGAATAATACTGGCCGCTGTGTCTACGCCTATCCCACATAATACAAAAC
              |TGTGCGAACCAGTAGTTCTGTACTATTGCGGTAAAAGGGATAGTACACTGGACTAGGAGC
              |CTGACTCGACTGGTGGAGTAAGTTCTTTCTTATCCGGATCCCCAAGGGGCAGAAAAAAAA
              |TGCTTGGTGGTCGACCTAGTGTCGTTCTCCACCATGACAAACAATCAAAAGCCCATGTAG
              |CGTGGATGAATCAAGGCGCCGATCCAGTGCTAAGATAGCCGAAGGAATACCAATTACAGA
              |CCATCGTCGTATCCTCGGGCCTCGCTGGCCCTCATCAATCTGGAAGAATAAGAACGAGCA
              |GTGGAGTCAATCGTACTCG
              |>Rosalind_0197
              |GGAAGGAGCGGAATAAAACAGGCTACCTTCTCTTAGTGGCGAGGGACATTCTCCTCAGAT
              |TTTTACACGAATAGGTACTCAGTCTCAATCCACGCAGGCGTCCTAGAAAGCTCAAACAGA
              |TCGGAGAGGCATACTCTCTGCCGTATCCGACTAAAAAAACGTCCGTAGGGTCTGTGCGCA
              |TCAGGACAAGTGGTAACCAAATGACCACAATGTCGGCCGTCGCGCTTATTAAGAAATGAA
              |TGGCCGACTGACAGTGCAAATAACAGCCTGACAGTATGCCAGTAGGGTCGACCATCAGCC
              |GCTATGCCTCTAGTCAAATATCTATGACTAGTTTTAGCGCGTTGGTGCTTGGCTCGCTTC
              |GCATGTAACAGCCACGACCGTGATGATTGATGAACGTCTTTCGCTTGACGACCCCCGGAC
              |ACTTACCTTCCCGGAGGTCGCTCAACGCCACCACTCGATTTCTCTTGACACTTGTTCTGT
              |ATACAAACGTCTGTAGGCGTATCGAGATCTGTACCTATATGACTGGCGCCGAAGCCCCCA
              |CCTAGAGTGTGAACCTCGGCCCTAATTTTCGAGAGACTTCAATCTAGAGATATGCCGCCG
              |GACTGCGGAACCGCAAGTTTAACGACCGGCTAGCCTACTGCCGAGGACTAGTTACGGGTG
              |TTCAATCCACAGCGCTGACAGAATTAAAGCGATGGGGGCCCCACACGCCCTAGGTGAATA
              |TTCCATGTCATACGGCCGTGTATAGCATTCAGCGCAATTGATCGATGCGGGTTGTATCTA
              |ATCTCCGACTGTCTACCTCAATCCTACATGATAAACTAGTCTCAGAGCTACTGTTTTGCT
              |CCAGATGGCAATATGCAATATGGACGATCCCTGCGGCTAATCCCAGATAGTTATACCATC
              |CATGCGCATACGCTCAGGAGAGCCCCGGCCCATCGGTAATGCCGTTGATCCTCCGCCTTT
              |GGACAAGGGCAACTCACTGAGCGCCATTGT
              |>Rosalind_8913
              |TGAAATTAGGCACTAGTACTGCACAGGTGATCAAAAACGGATCACTCGTGCGATTTTAGA
              |GCTGAGTCACCGCGGAAGCTGCCGACACACGCAACTATTTCTTTATAGAAACTTGTGTTC
              |CGACTTGCGTTCCCTGATTCACTACAAGTGTTAATGGGAGTACTCTTGACAATGTACTTA
              |CCTCTGATAAAGTAGTGAGTAGAATACGGCGACAGTTGGATACCGCGAATCTCTGGTCAG
              |CGGGAGAATATCTAGGCGTCAGCGGGATGCCCGCCATACCAGCCTGACTCGTCGTCCGGC
              |CGCTCTATTCCCTGGCTCGTAGGCACCGCGCACTCGGGTAGTACTGCCACATACCAGCTG
              |CGCGTCTGCGTTATAACCTGATGTCGGTCTCTAGGAATCGAACCGCCTACTCCCGAGCCG
              |TAGGTTTGCCATTATCCGATCGCGTGTGGAGGAGGTCCATACAACGAAGCTTGCGGCGAA
              |GTCTGCAATTTCTACAACTACCCCCCTTGGCCCTCCGTTGTTAGGGGACGATGACTCCGA
              |TGTGACGTTCGTATTATCGCTATGTTCATAACCGATGTCAATGATGCTAGGAAGACCTCC
              |GGTTTGCGCTGCATCCTCCGGTACATAGAAGTCGACTAAAAAAGGCGTATTATGGCGAGC
              |GTTGCAAGCATCGCGTCGGTCCCATGATGCGGTGAATGAGCGGAATTGTGTGTTATGGTG
              |AGGCTTCGACGAGCACCGAGAAAATATTACTTATATGCCTTAAGGTTTCTGCCGGACTTC
              |TGCTTATAGGTGAAAAGAAA
              |>Rosalind_4189
              |TTTGAGTCCTAAGCCAGCCCCCTACAACGAGTCCTACAAATACGGTCGAGCAGTACGTAC
              |GCGACTTGAGCCGGTGGTTATCTGCTATGACCAGTAGACCTACCAATAGCTGTTGGACAA
              |ATCCCGGCCGGCTAAAAGGGGTTGGTACCAAACCATTTTAATCACTGCAACATACATACT
              |GGACACTATGCACTGCTCCTTCAACGATGGAAGAGGTAAGGGAAGTCCAACTAGAGAGCT
              |CTGGCGTCTGAGGCGGAACTCTTCGGTTATACTCGCGCTCTCGTAGTCCGCTTGGGACGC
              |TTGAAAACTCAATCTTATGTTTGTCCGAAATACTAATCGGGTCTTTTTTTAGCGGACCCA
              |TAGTTCTGACCGGGCATCCCGTATCCTTCCTTTGCTCGTTCTTGGGCGACAATAGTTCCA
              |TGACAGGGAAAAAGTATATTCCTACCTTCTCTGAACCGGAGCTCCCCGATGTAGGTAGTA
              |ACAATCTACTACCTAGAACCCCCAGTATGTGCTTACGGGGACTGGCCTCGACGACAGCAT
              |TTACGCCATAGTACTGGTACGGTCTTTGTCTGGCAGATAGGTGCCGTATCATTAGCAACA
              |GTGAGCACGGAGCCACGCACATAACCGTCACGCGTTTTGGCAGTTAATTTAGATCGGGCG
              |TGATTGTCTCAGCCCAAGTTTGGTGTGAAGGGTCCTGATTCCTTAATCCTCTCTAATGAC
              |CTCCATTGTTGGGCTTGATATAGTGCCCCGGACGTTTACTTGGGTACGATTCCGTCGCGA
              |GTTACCCAGTAAGCAGACTCTATCCCACATGGCACATGCACGGATCTCCTCGTAGTGTCT
              |CGTACATGAGTGTCTGTGGCTCTTTGGGAGAGC
              |>Rosalind_1457
              |TCCAATAGTATACAAGGCGCATTTAATTCCCGTGGGAAATCCGCCTCAGAGGGGCTTCCG
              |GACCATGCTCTTTCGAGCTCCTGTAGACTTCTCTCCGGCCTTTGTCCAATAATCTATGGG
              |AATAGTGTGCCGTCAGCAGAACGGACCGTCTATATAGCACTCAACACATCGTTACTATAA
              |GGGAGACGTACCTCGTTTAGGCAAAGATCACGCTTCGACATCGCCTAATTTTCGATGCCT
              |AGAACAGAAGAGCCAAGGGCGGGCAACTTCCTTACAAAAAGCTGTCTGGGGCTTGTGAAA
              |TCACCGAGTCGAGCATTCTTATACCACTGAGGTATTTATATAAAGAGCGTGCCACATAGT
              |CCTCCACCGGGACCAACCATGGAATCTCAGAGCAATCGCGGCTTGCTTTGGCCCAAGCCG
              |ACATTTAAATTTAGTGAGGCAGTATGGGCTTTAGAACTGCGACTATCACCAACGCCCTAA
              |GTTAGGAGGGTCGAGGAGCCTCGCTAAGGTCATGGTTCCAAGGGGACGATAGTGGTTATT
              |GGAAGTCGGGGCTCCGGGAGAGTGCCGAAAGTCCAATGAGTACCTTACTAATGCGGCAGG
              |ACTACCGGATGCCTGGGTTCACCGACCGGCAGCTCTCGGAAATTACCGACCTCAAAGCGA
              |ATAGAGATGTGCTTATGTCGACGCTTGGACCAACCACCGCAACGGCTCGGTGCTCTATAG
              |GATTATGACCAAGTTCCCTGTCCGACATACTGGCCCCGGAAAGTATACCAAAGACCTCTA
              |GGACGCTCTAGAGTAGGGCCTTTACATTAAACCGCCCCTTGAACCAACGCCCGTAATGCT
              |AAATCTTGGGCAGCATCAAAGCAATCGGTGGTGGCGTTCGCGCAAGCCGTTTGTGCTTTG
              |ACTTTTTCCCCTATCCATTGGTAACCTGC
              |>Rosalind_8783
              |AGATTATCCGGAGGAGGATGTTGGTTGCACTTCTCTTAGACCTAGCTCAAGAATGTACTG
              |ACTTTTCCGCTCGGTACTACGCCAGTGCATTTCGACATCTCATAAACGTGTCGTGCCCCG
              |GACGACACTCCTGCTAACGGGTTGAGTGCTAAACCAAGGAATTGAGTATATAAAGTCTCA
              |CCACGTTCTCCTAGCCCAAGCCTAGACTAGCCCTACGGATCCAGACTTCGTGGTAGCATC
              |AGGTAGGAGTCTATGCGCCTATAATTTTGTGAGAACACACCCAGTAACGCCTTAGAGCTT
              |TGCGCTATACACCCACCCCTGTCGGTTCACTATTCGCAGTGACCAAGACCCCGCACTCGG
              |GCCAAGCTAGCGCAGCACAATGTACACTTTTAGGCTCCGGATAAACTCGGACTACTGGGG
              |CGCACATCCTAACAGGCGCCTCGATATGCACCCATACCGCGCCCTTTTCCAGATCATTCC
              |GACCCTGCAAACCTACTAAACCGAACCGCAGTGCCAGCTATATGGATAATCCTAATCCTT
              |GGGGAGTGCGGAACAAAAATTACCTCAAGATCTCACGAATATGAATTTGCACTATAAAAG
              |AGTGGCTTTCCAATTCGAGAGGTCTAGGTGTAGTGCCCCATATCTACCTGGGAATATAAG
              |CTGCGCATTTTGGCAATTTCGAGTGCAGCGAGTTTAGGATGTATAACCGCTGGTAAGAGG
              |GCCACACAACTACCAGTCTACCCCCGCGATGTATGCGTTGTGCTCTTAGTACATTCTGTG
              |TGTTCAGAACGCTCCACTAGCAATTGGGAAACGGCTTAGCTCTCTATATGAGTGAGAGTC
              |TTGGATGTCACAATAGGAGTCCCCCGAAATCCGGGTGAGAAAGTATGGCCCTACTAAAAT
              |TCAGTTTTTTTCAAGCTTCTCTCACTCAGGACGATACTAGGTATGTCATCTCTCTCAATC
              |AATCGTAAAGAACATTGTTGAAAGAGATAGAGAGTCT
              |>Rosalind_9247
              |GTAATAAGCGAGGAATTGATAATATCATATAGTCCCGGGGCGGTTTTTGCAGGGTTCTCC
              |GGGATACAGGCATCGTCGGTCCAGTCTTTAGGCTTGATCTCATGCCATCAGTCAGTGAGA
              |CTAAGTTTTAGGGCAAGCGTTTGCAATTAGTACCACAGGGGGTGTCGTGCCTGTTAATTG
              |TGTGAACAGTAACCTTACTCAGAGTGACACTAGCGTTCCTCTGTGGGACACCCGCAGGGG
              |AGAATGCCACAAGTCCGCGACCCGCCATGGTAGTTGGCCGCTGGAATGTTCGGTCGTACC
              |ATTCGGACTGAAGTAAAACGTGTTAGATGGAGCCAGGCCTCTTTTGTAATCCTTATGCGG
              |TTGCTGAATTGGCTGTGTAGAAAGAAACTACTTCCCGATCGAACTAGACGGCGGCGGAGA
              |CTTAAGGGTGGCACGGGTATGTGGCAATACAGTTGTAAGATGTTTTGGTGCACCAATGTG
              |TACGCCGTCGCCTAATTAATTCCGCGTAGGCATAATTGGGTACCAAATTGCGGGAAAGGG
              |TGTCTGGCTACGTACTAACTGTACAGCTGTGGAGCGATCCTCGACGGGGCTGACATATCG
              |AAGCTCGGACCGCTGCCGATTAGTTGTCGAGTTGCGGAATATTAATGACTCTTACAGTAG
              |CCGTCGGTCTCCAGTATAAGTGCCAAGGCCAATCGAGCGGCGCGCCCTTTGGCTCGGGGG
              |GCGATGACGGGCATCGCCTTGATTCAGCGTGCCTATAGAGTTAACTGTAATGACGATGCT
              |GCAGAGACCGCAGGTAGACAGTCCGGGTTAAGTGTACGCTGCGCGTGTTTTAATTATCTT
              |TACAAAATAACGCTCTGTGAAGCACTTATTAATAGCGTGTATCACTGAGTCCCG
              |>Rosalind_0149
              |GCGCCAACTGTTTTAAGGATATAAAATGTACCAGGTGACGATACGGGTCACTCACATCAT
              |ACGGCCAGACTCCTTCGTGGGGCAGGCGTGGCTCTGCGTGGATGCGTTGCATGGTACGAT
              |TCCCGCGGCCCACGATGCGCTGCCTAACATTGATGTTCACTTGTCAGGTCTATCGTAGCA
              |AAGCGTTTAATGTGCACACGGCATCGATTCCAGATATTTAGGTTCCACCCAGGCACCCCA
              |AACCGGCTGATTTTCATCGGTGGAGCACGCGTCGAAGTGGGCGAGTTTAATCTAGGACCC
              |AGTACCGCCTCTATTGCCTGTCGCAGTTAAAAGGCTGCCATTCAATACCTGCATCCGAAA
              |CCAACTATTGGCGTACCGAGGAACACCAACTTTTAACACTTTAGGCACGTGCAGGGTTGG
              |ACCAAGTCGGAGACTCATGTCCACAACTCTCCATTGTTCGCTCAACAGTGAGCCATGGCA
              |TGGCAGGTGTCACATGTGAGAACGCCATCGAGGGTAGCGTTTCTACCGTGAGGAGTCATA
              |AAACATGAAACTGAACACCGTCGCTTTAAGGAGGGTAAACTACACAATAGCCTGACCCGT
              |GATCTTTAGCTCCACGGCCTGGGTAATCTTGCAACTCCATGGTTTATCCTCCAGGATTGC
              |ATCATGAACGTAGTTGGTACATCTTGGCAGGCTGGGCAAAAACCGAGGCGCCTGAAATAC
              |TGTGCTTCACTTTTGAATAGGCCGGCGCTTGTAATCCTGTAACAGCGAGTGCATCTCGCC
              |TAGATGGTGTTGACCCGTGGACCCATAGCAGTGGTAGGAAGAATCTGCGTTGATCTACAT
              |CC
              |>Rosalind_0909
              |TGGTTGTGCGACCGAATTATTTGGTCTGAGATGTTTCATCGAAATCGATTAGCCCTGTTC
              |AATTGTAGAATAGGAATTATCTGCCCGGATTCAATCGCCAAACAGCAGGTACATTCTATC
              |TCGTTAGTATATGCATTATGCCCAGGTTTTTTCCTTCCAAGCGCCGTGCTGACGTAAGTG
              |TGCGCTAAGTGCCGGCAAGCCCAGGCTTCTCTCTCCAATTTCACGGTTTGTTAGAGTTCA
              |GCTAGGTATACTTCCGAAAAGCGACTCTGGCATTCGCCTATAAGGAATAGGAAGTCGCAA
              |CAGCGCTAACGGCAGGGAGGCCTAGTTTCACCACAGACACATCAAGTCCTTGAGAAGCCT
              |TCAAATGCTCACTGACGATTCCTGGAGCCTCGGTGTGCTCCGAGTATCAAGCTACAGGGG
              |TCTCCTGATCGAAGGACGCCGATCGGAAAACTACATACCGTACTTTCGGAAATGGGTCCT
              |GTAAGTCATAGAATTACAGTGGTCGGACTCAGGTGTTTTTCTAGAGCTGAAGGCACGTTC
              |GTCTTCAATGATCTAGCGGAAGTTGGATGAGACATTAGTACGTCCGTTCTGATAAGTAGA
              |GTGTTGGTTTACTCTTATGAGAGTTCTTACAAACTCTAGGGGACAGTGGTTCGACTACGT
              |ATCTATCGTGCCTGTTAAGATACAGAAGTATCAGGTCGGGCACCGTGCACTGCCAGCTCA
              |CAATTAGAGTAAATTACGATTCAGAGCGTCCGGCGACGGGCGCTGTTGTAGTCTTTGCCA
              |CGCCGTGGAGATTTGGTGAGCACGCGTCGGATTTGAACTTGACCGACGAACTGACTAAAC
              |GGTCCTACGGGAATCCGTCAGGTCACACTCAAAACATCGAATAACTGT
              |""".stripMargin

        val GCs = (s split ">").tail map { L =>
            val e = L split "\r\n"
            val seq = e.tail mkString ""

            val (gc, all) =
                seq.foldLeft((0,0)) {
                    case ((gc, all), x) =>
                        if (x == 'C' || x == 'G')
                            (gc + 1, all + 1)
                        else if (x == 'A' || x == 'T')
                            (gc, all + 1)
                        else
                            (gc, all)
                    }

            (e.head, 1.0 * gc / all)
        } maxBy { _._2 }

        println(GCs._1)
        println(GCs._2 * 100)

    }

}
