object revc {

    def main(args : Array[String]) {

        val s = "GGGGTTGCCCGAAGAGCCCACTAAAATACCTTACATTACGACACCGAACGAGGCGGCAATGTGATGGACGGTCGAGCGTGGGCTCCCTTGTGCCGGGGCACGCGTTCTCATTCTCTGGCATCTTGATTATTTAACGCTGTGTCCTGATATTAACTAGTGCGGGGCGTTACGGGGCCGCCGGACCTGGAAGTAAGACTGTCAGGGGTTTCATGTACACCGCTATGTAAATGGTAACGGCACAAGCGTCAACGCAGACAAGAACTCTTGAAGTTAACTGGCAGACCACTCTATACTGCTGTCGGCACTTAATGGCACTTTGAAGAAGGCACCATGCTAACTAACGGCCATGCAGGAGGTAGCTTTAGCAGCGAGTAACACGTATCCTCGCTGTGGAACAAGCAATGCGAACAGGGCCGGGGGAAGAACATCAACTTAAGTGGAGTGCAGGTATATTGACGAACAAAGGGCATGCCAAAAGGCCCTTGCAACCCGCCTGTGCTACTGCAAATGCCCCTTTTGTGGGTTCAGCCTTCGGACCAGTCTATGACTCCTCGAACGTACCGTGGTGGCCATTATATTATCGCAGTCTAAATTACAAGCGGAGACTCCCCCCCACGAACCAAAGAACCGAGATCACCTCGACCGTCCTGTCTGCGTGTAAGCGGATAGCGAATTACAAAGTTTGAGTATGTTCTGGAGATGAGGTCGTGGACCGATGGTGATGTGGAAATAGCTGCCGAAATCTGAATCGTTTACACAACGCCAGAGAGGCAAGCGATACATTGGCTTCAATGAGGCGTGAAACGGCGTTTGTC"

        def rev(s : String) = s.reverseMap({
            case 'A' => 'T'
            case 'T' => 'A'
            case 'C' => 'G'
            case 'G' => 'C'
        }).toString

        print(rev(s))
    }

}
