object rna {

    def main(args : Array[String]) {

        val s = "GGATGGCTAAGGACAGCAGATAAGTAAACAGCTAGACGTGTACTCCATTAGCTGATTCTTTCTCTGCAACGAAGCCAATTGGGCAGAAAGTGTGCTGACCTGCATCGTTGTTTTGGCATGATTTGAAATACGCGGAAATAGTCTGTTTAGGTGGGGTCGTCCAGGCGCTCTATCACTAGGGAGTACGAACTGGCTTGCATCTACTCCTGCGCTCAAAAGTTCACTACTTTGCCTGACCACTAGGCAAGTGTCCCTAGGTACTGGCTCCTGACTTACAGGGCGTTGTGCAAGTATGTGTGAGGCGCTAAAAAAGTTCTATTAAAGGGTCCAGTGGTAAGTACTGTTCCGAACGGTACCTCAGTGAGAATAGATAAACGAACAGTTGATCCCGACGGCATATGCATTCGTCTCCGAGCCAGCACTGAGGGTGCAGAAATAGCAACCCATTAATTGTCTACACCGGCATCGGCTTATGACAAGGCATCAATAGTCCCGGGTAAGTATGACCTGGAATTCTGGCCGCTACGCCCCTACTAAAGTTTATGAATGTATTGGTGAGCATAGTTTATGTAGTGCTGATCGACCACGTCATTCACTACTCTTCCAACACTTACCAGTACTCATCCCAAATCAGATCTCGTAAGAGAATCGACTTTAATACGTTCCTGGCAACTCCCTCGTCCGTTTTCCCTTGTATGCCGTATCGTCTTAGCCGCTCCACGGACCATCTGTGGGGTCGCCGCATTTCTAGTCTCTAATGTTCCCTTTGGGAGGTCTTAGAGTTAAGCTCACCGTTCCGTCGAGCCAATGATATTAAACCGAGAGAAAGCCTTTCGGACCTAACCGCACGAATTGACCTTATTCCGCATTGTTTCTGTACCTTGCTCTATCGCGTCGTTCACACTGACAAGCCGTAGTCACAACGACTTCACCTGAAAGTTACC"

        def transform(s : String) = s map {
            case 'T' => 'U'
            case x => x
        }

        print(transform(s))
    }

}
