
object subs {

    def main(args : Array[String]) {

        val s = "CCTGAGAAGGGGGAGCAAGGGGGAAGGGGGCCAAGGGGGAAAAAGGGGGTTCAGAAGGGGGTTAAGGGGGAAGGGGGAAGGGGGTAGAAAAAAGGGGGCCGTGCTTAAAGGGGGGGTAAAGGGGGAAGGGGGGAAGGGGGAAGGGGGAAGGGGGTAAGGGGGTGTAAGGGGGTGAAGGGGGATAAAGGGGGTCAAGGGGGAGAAAAGGGGGCTTAAAGGGGGGAAGGGGGAAGGGGGGAAAGGGGGCAAGGGGGAAGGGGGAAGGGGGATCCTTAAAGGGGGCTGAAGGGGGACGGTAGCAAGGGGGAAGGGGGTTTGTGCACGAATGAAAGGGGGACGAAAGGGGGGAAGGGGGAAAGGGGGAAGGGGGATCAAGGGGGACAAGGGGGACTACAAGGGGGACCAAAGGGGGAAAGGGGGAGCTAAGGGGGGTCGAAAGGGGGTAAGGGGGTATTATTAAGGGGGAAGGGGGAAGGGGGAAGGGGGAAGGGGGACAATAAGGGGGAAGGGGGCAAGGGGGATAAGGGGGGGACCAAGGGGGAAAGGGGGTCAGAAGGGGGAGAAGGGGGTAAGGGGGAAGGGGGTCGTCAAGGGGGAGAAGGGGGCTCAAGGGGGATAAGGGGGGAAGGGGGTTTTAAAGGGGGAAAGGGGGAAGGGGGTAAGGGGGAAGGGGGAAGCAAGGGGGAAGAAGCGTCAAGGGGGTGGATTAGACTGCAAAGGGGGTGTGAAGGGGGGAAGGGGGAAGGGGGGCAAGGGGGTGCAAGGGGGCGAAAGGGGGCACAAGGGGGAAGGGGGTAAGGGGG"
        val pat = "AAGGGGGAA"

        def positions(idx : Int = 0) : List[Int]
            = s.indexOf(pat, idx) match {
                    case -1 => Nil
                    case x => (x + 1) :: positions(x + 1)
                }

        println(positions() mkString " ")

    }

}
